/*:
 
 # CARBON FOOTPRINT

 I'm Ranga 👋. This playground makes awareness of **Climate Change** and tells the importance of knowing their carbon emissions by calculating their carbon footprint and suggesting different strategies to offset their carbon footprint.
 
 ## About
 
 From pollution to overpopulation, human activities drive up the Earth's temperature and fundamentally change the world around us.

 The leading cause is a phenomenon known as the **Greenhouse Effect**. Gases in the atmosphere such as water vapor, carbon dioxide, methane, nitrous oxide, and chlorofluorocarbons let the sun's light in but keep some of the heat from escaping. The more greenhouse gases in the atmosphere, the more heat gets trapped, strengthening the greenhouse effect and increasing the Earth's temperature.

 A **Carbon Footprint** is the total amount of greenhouse gases (including carbon dioxide and methane) generated by our actions.

 Solving climate change requires reducing carbon emissions. When you offset your footprint, you neutralize your emissions by protecting forests that absorb carbon from the atmosphere. Carbon emissions from your lifestyle choices, from transportation to diet, impact the climate. Carbon emissions a global problem, but you can be a part of the solution.

 ## Goals of the playground.

 ♻️  Offset carbon emission by an individual.
 
 ♻️ To spread awareness and urgency of action.
 
 - Note:This Playground is complete built using SwiftUI

 ## Topics what will learn you throughout the playground are?


 🌟 Game Development
 
 🌟  Design
 
 🌟  Animations
 
 🌟 Building Custom Shapes
 
 🌟 SceneKit
 
 🌟 AVKit 

 ## Things to play around within this playground:
 
 Chapter 0: 👾 The Easiest Way to tackle Climate Change
 
 Chapter 1: 🦶 Calculate your Carbon Footprint
 
 Chapter 2: ♻️ Offset your Carbon Footprint
 
 Chapter 3: 🧗‍♀️ Get Inspired for going Carbon Neutral

 */
//: Let's start with the [Eaiest Way!](@next)
